#include <bonk/mods/WorseGravity.hpp>

namespace bm {
    void WorseGravity::deactivate() {
        if (notInScene())
            return;
        auto playerConst = getMario()->mPlayerConst;
        playerConst->mGravity = originals[0];
        playerConst->mJumpGravityCapCatch = originals[1];
        playerConst->mGravityDamage = originals[2];
        playerConst->mGravityMove = originals[3];
        playerConst->mGravitySpinAir = originals[4];
        playerConst->mDamageFireGravity = originals[5];
        playerConst->mJumpGravity = originals[6];
        playerConst->mTrampleGravity = originals[7];
        playerConst->mTrampleHighGravity = originals[8];
        playerConst->mTrampleGravity2D = originals[9];
        playerConst->mTrampleHighGravity2D = originals[10];
        playerConst->mTrampleHipDropGravity = originals[11];
        playerConst->mCapLeapFrogJumpGravity = originals[12];
        playerConst->mCapHeadSpringJumpGravity = originals[13];
        playerConst->mCapHeadSpringJumpGravityHigh = originals[14];
        playerConst->mJumpGravity2nd = originals[15];
        playerConst->mJumpGravity3rd = originals[16];
        playerConst->mSpinFlowerJumpGravity = originals[17];
        playerConst->mJumpGravityForceRun = originals[18];
        playerConst->mCapCatchPopGravity = originals[19];
        playerConst->mSquatJumpGravity = originals[20];
        playerConst->mTurnJumpGravity = originals[21];
        playerConst->mLongJumpGravity = originals[22];
        playerConst->mGravityAir = originals[23];
        playerConst->mGravityWallSlide = originals[24];
        playerConst->mWallJumpGravity = originals[25];
        playerConst->mWallClimbGravity = originals[26];
        playerConst->mWallClimbJumpGravity = originals[27];
        playerConst->mGrabCeilLeavePopGravity = originals[28];
        playerConst->mGrabCeilJumpGravity = originals[29];
        playerConst->mSpinJumpGravity = originals[30];
        playerConst->mHipDropGravity = originals[31];
        playerConst->mHeadSlidingGravityAir = originals[32];
        playerConst->mSwimGravity = originals[33];
        playerConst->mSwimGravityWalk = originals[34];
        playerConst->mSwimSurfaceGravity = originals[35];
        playerConst->mSwimHeadSlidingGravity = originals[36];
        playerConst->mSwimJumpHipDropGravity = originals[37];
        playerConst->mDamageSwimGravity = originals[38];
        playerConst->mDamageSwimSurfaceGravity = originals[39];
    }
    void WorseGravity::apply() {
        auto playerConst = getMario()->mPlayerConst;
        originals[0] = playerConst->mGravity;
        originals[1] = playerConst->mJumpGravityCapCatch;
        originals[2] = playerConst->mGravityDamage;
        originals[3] = playerConst->mGravityMove;
        originals[4] = playerConst->mGravitySpinAir;
        originals[5] = playerConst->mDamageFireGravity;
        originals[6] = playerConst->mJumpGravity;
        originals[7] = playerConst->mTrampleGravity;
        originals[8] = playerConst->mTrampleHighGravity;
        originals[9] = playerConst->mTrampleGravity2D;
        originals[10] = playerConst->mTrampleHighGravity2D;
        originals[11] = playerConst->mTrampleHipDropGravity;
        originals[12] = playerConst->mCapLeapFrogJumpGravity;
        originals[13] = playerConst->mCapHeadSpringJumpGravity;
        originals[14] = playerConst->mCapHeadSpringJumpGravityHigh;
        originals[15] = playerConst->mJumpGravity2nd;
        originals[16] = playerConst->mJumpGravity3rd;
        originals[17] = playerConst->mSpinFlowerJumpGravity;
        originals[18] = playerConst->mJumpGravityForceRun;
        originals[19] = playerConst->mCapCatchPopGravity;
        originals[20] = playerConst->mSquatJumpGravity;
        originals[21] = playerConst->mTurnJumpGravity;
        originals[22] = playerConst->mLongJumpGravity;
        originals[23] = playerConst->mGravityAir;
        originals[24] = playerConst->mGravityWallSlide;
        originals[25] = playerConst->mWallJumpGravity;
        originals[26] = playerConst->mWallClimbGravity;
        originals[27] = playerConst->mWallClimbJumpGravity;
        originals[28] = playerConst->mGrabCeilLeavePopGravity;
        originals[29] = playerConst->mGrabCeilJumpGravity;
        originals[30] = playerConst->mSpinJumpGravity;
        originals[31] = playerConst->mHipDropGravity;
        originals[32] = playerConst->mHeadSlidingGravityAir;
        originals[33] = playerConst->mSwimGravity;
        originals[34] = playerConst->mSwimGravityWalk;
        originals[35] = playerConst->mSwimSurfaceGravity;
        originals[36] = playerConst->mSwimHeadSlidingGravity;
        originals[37] = playerConst->mSwimJumpHipDropGravity;
        originals[38] = playerConst->mDamageSwimGravity;
        originals[39] = playerConst->mDamageSwimSurfaceGravity;
    }
    void WorseGravity::control() {
        Mod::control();
        auto playerConst = getMario()->mPlayerConst;
        f32 modifier = par::get("WorseGravityModifier", 1.0f);
        playerConst->mGravity = originals[0] * modifier;
        playerConst->mJumpGravityCapCatch = originals[1] * modifier;
        playerConst->mGravityDamage = originals[2] * modifier;
        playerConst->mGravityMove = originals[3] * modifier;
        playerConst->mGravitySpinAir = originals[4] * modifier;
        playerConst->mDamageFireGravity = originals[5] * modifier;
        playerConst->mJumpGravity = originals[6] * modifier;
        playerConst->mTrampleGravity = originals[7] * modifier;
        playerConst->mTrampleHighGravity = originals[8] * modifier;
        playerConst->mTrampleGravity2D = originals[9] * modifier;
        playerConst->mTrampleHighGravity2D = originals[10] * modifier;
        playerConst->mTrampleHipDropGravity = originals[11] * modifier;
        playerConst->mCapLeapFrogJumpGravity = originals[12] * modifier;
        playerConst->mCapHeadSpringJumpGravity = originals[13] * modifier;
        playerConst->mCapHeadSpringJumpGravityHigh = originals[14] * modifier;
        playerConst->mJumpGravity2nd = originals[15] * modifier;
        playerConst->mJumpGravity3rd = originals[16] * modifier;
        playerConst->mSpinFlowerJumpGravity = originals[17] * modifier;
        playerConst->mJumpGravityForceRun = originals[18] * modifier;
        playerConst->mCapCatchPopGravity = originals[19] * modifier;
        playerConst->mSquatJumpGravity = originals[20] * modifier;
        playerConst->mTurnJumpGravity = originals[21] * modifier;
        playerConst->mLongJumpGravity = originals[22] * modifier;
        playerConst->mGravityAir = originals[23] * modifier;
        playerConst->mGravityWallSlide = originals[24] * modifier;
        playerConst->mWallJumpGravity = originals[25] * modifier;
        playerConst->mWallClimbGravity = originals[26] * modifier;
        playerConst->mWallClimbJumpGravity = originals[27] * modifier;
        playerConst->mGrabCeilLeavePopGravity = originals[28] * modifier;
        playerConst->mGrabCeilJumpGravity = originals[29] * modifier;
        playerConst->mSpinJumpGravity = originals[30] * modifier;
        playerConst->mHipDropGravity = originals[31] * modifier;
        playerConst->mHeadSlidingGravityAir = originals[32] * modifier;
        playerConst->mSwimGravity = originals[33] * modifier;
        playerConst->mSwimGravityWalk = originals[34] * modifier;
        playerConst->mSwimSurfaceGravity = originals[35] * modifier;
        playerConst->mSwimHeadSlidingGravity = originals[36] * modifier;
        playerConst->mSwimJumpHipDropGravity = originals[37] * modifier;
        playerConst->mDamageSwimGravity = originals[38] * modifier;
        playerConst->mDamageSwimSurfaceGravity = originals[39] * modifier;
    }
} // namespace bm
